server:
  port: 9090

spring:
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthDb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${secretKeyjava12}
  issuer: ${issuerjava12}

rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  register-bindingKey: registerBindingKey
  activation-mail-queue: activationMailQueue
  activation-mail-bindingKey: activationMailBindingKey
  activation-queue: activationQueue
  activation-bindingKey: activationBindingKey