server:
  port: 9093

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: myemail
    password: mypass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
