server:
  port: 9091

spring:
  cache:
    type: redis
  data:
    mongodb:
      host: localhost
      port: 27020
      username: java12user
      password: root
      database: UserDb
    redis:
      port: 6379
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service


jwt:
  secretKey: ${secretKeyjava12}
  issuer: ${issuerjava12}

rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  activation-queue: activationQueue
  register-bindingKey: registerBindingKey
  activation-bindingKey: activationBindingKey
  elastic-save-bindingKey: elasticSaveBindingKey
  elastic-queue: elasticQueue
  elastic-exchange: elasticExchange